version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media:/app/media
volumes:
  static_volume:
  media: